<div class="header_inner">
    <nav class="nav">
        <a class="nav_link" href="/admin">Главная</a>
        <a class="nav_link" href="/admin/head/admin/administrate">Администрирование</a>
        <a class="nav_link" href="/admin/head/catalog/show">Каталог</a>
        <a class="nav_link" href="/admin/head/order">Заказы</a>
        <a class="nav_link" href="/admin/user/logout">Выйти</a>
    </nav>
</div>
