<?php
/**
 * @var $options array
 */
?>
<div class="sidebar">
    <?php include_once 'administrate_sidebar.phtml'?>
</div>
<?php if ($options['data'] !== null): ?>
        <table border="1" cellpadding="5" cellspacing="0" width="100%">
            <tr>
                <th>№</th>
                <th>Аватар</th>
                <th>Имя</th>
                <th>Дата Рождения</th>
                <th>Почта</th>
                <th>Телефон</th>
                <th>Аддресс</th>
                <th>Статус доступа</th>
            </tr>
            <?php
            $i = 1;
            foreach ($options['data'] as $admin):
            ?>
                <tr>
                    <td><?= $i++ ?></td>
                    <td>
                        <?php if ($admin['image'] !== null) : ?>
                        <img src="/Media/images/admin_users/<?= $admin['image'] ?>" alt="avatar" width="150px" height="150px">
                        <?php else : ?>
                        Аватар не выбран
                        <?php endif; ?>
                    </td>
                    <td><?= $admin['name'] ?></td>
                    <td><?= $admin['birthdate'] ?></td>
                    <td><?= $admin['email'] ?></td>
                    <td><?= $admin['phone'] ?></td>
                    <td><?= $admin['address'] ?></td>
                    <td>
                        <?php if ($admin['is_approved'] === '1'):?>
                            Имеет Доступ
                        <?php else: ?>
                            Без Доступа
                        <?php endif; ?>
                    </td>
                </tr>
            <?php  endforeach; ?>
        </table>
<?php endif; ?>
