<?php
/**
 * @var $options array
 * @var $this Views\ProjectViews\Admin\UserView
 */
?>
<div class="sidebar">
    <?php include_once 'user_sidebar.phtml'?>
</div>

<div>
    <?php
    foreach ($options['data'] as $field => $value) {
        echo $this->changesOfUserProfileItems($field, $value);
    }
    ?>
</div>
<?php //foreach ($options['data'] as $field => $value): ?>
<?php //if ($field === 'image') {
//    //придумать как вставить условие для картинки
//    echo "<img src='/Media/images/admin_users/{$value}' alt='avatar' width='150px' height='150px'>";
//    } else {
//    echo $value;
//    }?><!--<br>-->
<!--    <form action="/admin/user/update/admins/--><?//= $field ?><!--" method="post" --><?php //if ($field === 'image') {
//        echo "enctype='multipart/form-data'";
//    }?><!-- >-->
<?php //if ($field === 'pass'): ?>
<!--        <label>Старый пароль :</label>-->
<!--        <input name="old_pass" type="password" placeholder="Ваш старый пароль"/>-->
<!--        <br>-->
<!--        <label>Новый пароль:</label>-->
<!--        <input name="pass" type="password" placeholder="Ваш новый пароль"/>-->
<!--        <br>-->
<!--        <label>Подтверждение пароля:</label>-->
<!--        <input name="pass_confirm" type="password" placeholder="Подтверждение нового пароля"/>-->
<!--        <br>-->
<?php //elseif ($field === 'image'):?>
<!--        <input name="--><?//= $field ?><!--" type="file"/>-->
<?php //else:?>
<!--        <input name="--><?//= $field ?><!--" type="text" --><?php //if ($field === 'phone') {
//            echo "value='+380'";
//        }?><!--/>-->
<?php //endif;?>
<!--        <button type="submit">Изменить</button>-->
<!--    </form>-->
<?php //endforeach; ?>
<?php
//    foreach ($options['data'] as $field => $value) {
//        echo $value . '<br>';
//        ?>
<!--        <form action="/admin/user/update/admins/--><?//= $field ?><!--" method="post">-->
<!--            <label>Логин:</label>-->
<!--            <input name="--><?//= $field?><!--" type="text" placeholder="Ваш логин"/>-->
<!--            <br>-->
<!--            <button type="submit">Изменить</button>-->
<!--        </form>-->
<?php //} ?>
