<?php /** @var $options array */ ?>
<h1>Добро пожаловать! Авторизируйтесь на сайте.</h1>
<form action="admin/admin/login/admins" method="post">
    <label>Логин:</label>
    <input name="login" type="text" placeholder="Ваш логин"/>
    <br>
    <label>Пароль:</label>
    <input name="pass" type="password" placeholder="Ваш пароль"/>
    <br>
    <label>Пароль админа:</label>
    <input name="admin_pass" type="password" placeholder="Пароль админа"/>
    <br>
    <button type="submit">Войти</button>
</form>
