<?php /** @var $options array */ ?>
<h2>Пройди регистрацию О ВЕЛИКИЙ!</h2>

<form action="/admin/admin/new/admins" method="post" enctype="multipart/form-data">
    <label>Логин(только латинские буквы и цифры,от 4 до 16 символов):</label>
    <input name="login" type="text" />
    <br>
    <label>Пароль(только латинские буквы и цифры,от 4 до 16 символов):</label>
    <input name="pass" type="password" />
    <br>
    <label>Подтверждение пароля:</label>
    <input name="pass_confirm" type="password" />
    <br>
    <label>Пароль подтверждающий,что вы Админ(знают только Админы):</label>
    <input name="admin_pass" type="password" />
    <br>
    <label>Ваше полное имя(только латинские буквы или только кириллица):</label>
    <input name="name" type="text" />
    <br>
    <label>Дата рождения(День.месяц.год = 01.01.2000):</label>
    <input name="birthdate" type="text" />
    <br>
    <label>Ваш e-mail:</label>
    <input name="email" type="text" />
    <br>
    <label>Ваш мобильный телефон:</label>
    <input name="phone" type="text" value="+380"/>
    <br>
    <label>Ваш адресс:</label>
    <input name="address" type="text"/>
    <br>
    <label>Аватарка (необязательно!):</label>
    <input name="image" type="file"/>
    <br>
    <button type="submit">Зарегистрировать</button>
</form>