<div class="header_inner">
    <nav class="nav">
        <a class="nav_link" href="/">Главная</a>
        <a class="nav_link" href="/catalog">Каталог</a>
        <a class="nav_link" href="/user/authorization">Авторизация</a>
        <a class="nav_link" href="/user/registration">Регистрация</a>
        <a class="nav_link" href="/about">О нас</a>
        <a class="nav_link" href="/basket">Корзина</a>
    </nav>
</div>
